# Generated by Django 5.2.8 on 2025-11-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('topic', models.CharField(choices=[('history', 'History'), ('government', 'Government & Politics'), ('culture', 'Culture & Society'), ('geography', 'Geography & Places'), ('other', 'Other')], default='other', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('hardest', 'Hardest'), ('cheatsheet', 'Cheat Sheet')], default='general', max_length=20)),
            ],
        ),
    ]
