# Generated by Django 5.2.8 on 2025-11-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
