# Generated by Django 5.2.8 on 2025-11-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('hardest', 'Hardest'), ('cheatsheet', 'Cheat Sheet'), ('common', 'Common Questions')], default='general', max_length=20),
        ),
    ]
