# Generated by Django 5.2.8 on 2025-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.CharField(blank=True, choices=[('kings', 'Kings & Queens'), ('wars', 'Wars'), ('gov', 'Government'), ('geo', 'Geography'), ('mixed', 'Randon'), ('other', 'Other')], help_text='(Kings, Wars, Gov...ect)', max_length=20, null=True),
        ),
    ]
