# Generated by Django 5.2.8 on 2025-11-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Book', 'Book Based'), ('general', 'General'), ('hardest', 'Hardest'), ('cheatsheet', 'Cheat Sheet'), ('common', 'Common Questions')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.CharField(blank=True, choices=[('kings', 'Kings & Queens'), ('wars', 'Wars'), ('gov', 'Government'), ('geo', 'Geography'), ('mixed', 'Random'), ('other', 'Other')], help_text='(Kings, Wars, Gov...ect)', max_length=20, null=True),
        ),
    ]
