# Generated by Django 5.2.8 on 2025-11-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_category_alter_question_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('book', 'Book Based'), ('general', 'General'), ('hardest', 'Hardest'), ('cheatsheet', 'Cheat Sheet'), ('common', 'Common Questions')], default='general', max_length=20),
        ),
    ]
