# Generated by Django 5.2.8 on 2025-11-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('hardest', 'Hardest'), ('cheatsheet', 'Cheat Sheet'), ('common', 'Common Questions'), ('book', 'Book Based')], default='general', max_length=20),
        ),
    ]
