# Generated by Django 5.2.8 on 2025-11-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodesession',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='bookmodesession',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookmodesession',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmodesession',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmodesession',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
